steps:
- id: "Installing docker-compose"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/docker-compose:latest'
  - '.'

- id: "Running docker-compose"
  name: 'gcr.io/$PROJECT_ID/docker-compose'
  args: ['-f','docker-compose.yaml','up','-d','--build']

- id: "Running ps"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'ps'

- id: "Running migrations"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'exec'
  - '-t'
  - 'app'
  - 'php'
  - '/var/www/artisan'
  - 'migrate'

- id: "Running tests"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'exec'
  - '-t'
  - 'app'
  - 'php'
  - '/var/www/vendor/bin/phpunit' 
  - '-c'
  - '/var/www/phpunit.xml'

- id: "Removing .env"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'exec'
  - '-t'
  - 'app'
  - 'rm'
  - '-f' 
  - '-f' 
  - '/var/www/.env'

- id: "Rename image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'workspace_app:latest', 'gcr.io/$PROJECT_ID/sso:$SHORT_SHA']

- id: "Pushing  Image"
  name: 'gcr.io/cloud-builders/docker'
  args: ['push','gcr.io/$PROJECT_ID/sso:$SHORT_SHA']

- id: Ajust deployment for kubectl
  name: 'gcr.io/cloud-builders/gcloud'  
  entrypoint: '/bin/sh'  
  args:
    - '-c'
    - |
      sed 's#img-app-deployment#gcr.io/$PROJECT_ID/sso:$SHORT_SHA#g' ./k8s/app-deployment.yaml > k8s/app-deployment-new.yaml; 
      cat k8s/app-deployment-new.yaml;

- id: "Deploying to kubernetes"
  name: 'gcr.io/cloud-builders/kubectl'
  args: 
  - 'apply'
  - '-f'
  - 'k8s/app-deployment-new.yaml'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=standard-cluster-1'
  
images:
- 'gcr.io/$PROJECT_ID/docker-compose:latest'